upstream was_pool {
    server was:8080 max_fails=1 fail_timeout=10s;
}

server {
    listen 80;

    location / {
        proxy_pass http://was_pool;
        proxy_connect_timeout 1s;
        proxy_next_upstream error timeout;
        proxy_set_header Host $host;
    }
}
