# ==============================================================================
# [SKALA K8s Lab] ch07-service/service.yaml : L4 내부 로드밸런서 Service
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: shop-api
  namespace: skala-gj4
  labels:
    app: shop-api
spec:
  type: ClusterIP
  selector:
    app: shop-api
  ports:
    - name: http
      port: 80
      targetPort: http
